name: CI/CD Pipeline

env:
    AWS_REGION: us-east-1

on:
    push:
        branches:
            - main

jobs:
    ci:
        name: Build & Scan Docker Images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Docker images
              run: |
                  docker build -t public.ecr.aws/t4h0a4r3/url-shortener-shortener:${{ github.sha }} ./shortener-service
                  docker build -t public.ecr.aws/t4h0a4r3/url-shortener-redirect:${{ github.sha }} ./redirect-service
                  docker build -t public.ecr.aws/t4h0a4r3/url-shortener-frontend:${{ github.sha }} ./frontend

            - name: Scan shortener service
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: public.ecr.aws/t4h0a4r3/url-shortener-shortener:${{ github.sha }}
                  format: "json"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Scan redirect service
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: public.ecr.aws/t4h0a4r3/url-shortener-redirect:${{ github.sha }}
                  format: "json"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Scan frontend service
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: public.ecr.aws/t4h0a4r3/url-shortener-frontend:${{ github.sha }}
                  format: "json"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::586794451190:role/GithubActionsRole-url-shortener
                  aws-region: ${{ env.AWS_REGION }}

            - name: Log in to Amazon ECR
              run: |
                  aws ecr-public get-login-password --region ${{ env.AWS_REGION }} \
                  | docker login --username AWS --password-stdin public.ecr.aws

            - name: Push Docker images to Amazon ECR
              run: |
                  docker push public.ecr.aws/t4h0a4r3/url-shortener-shortener:${{ github.sha }}
                  docker push public.ecr.aws/t4h0a4r3/url-shortener-redirect:${{ github.sha }}
                  docker push public.ecr.aws/t4h0a4r3/url-shortener-frontend:${{ github.sha }}

    # cd:
    #     name: Deploy to ECS
    #     runs-on: ubuntu-latest
    #     needs: ci
    #     permissions:
    #         contents: read
    #         id-token: write

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Configure AWS credentials (OIDC)
    #           uses: aws-actions/configure-aws-credentials@v4
    #           with:
    #               role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
    #               aws-region: us-east-1

    #         - name: Deploy ECS services
    #           run: |
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service shortener-service \
    #                 --force-new-deployment
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service redirect-service \
    #                 --force-new-deployment
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service frontend-service \
    #                 --force-new-deployment
