name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    ci:
        name: Build & Scan Docker Images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::586794451190:role/GithubActionsRole-url-shortener
                  aws-region: us-east-1

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker images
              run: |
                  docker build -t ${{ steps.login-ecr.outputs.registry }}/shortener:${{ github.sha }} ./shortener-service
                  docker build -t ${{ steps.login-ecr.outputs.registry }}/redirect:${{ github.sha }} ./redirect-service
                  docker build -t ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }} ./frontend

            - name: Scan Docker images with Trivy
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: ${{ steps.login-ecr.outputs.registry }}/shortener:${{ github.sha }}
                  format: "table"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Scan redirect service
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: ${{ steps.login-ecr.outputs.registry }}/redirect:${{ github.sha }}
                  format: "table"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Scan frontend service
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}
                  format: "table"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            # - name: Push Docker images to Amazon ECR
            #   run: |
            #       docker push ${{ steps.login-ecr.outputs.registry }}/shortener:${{ github.sha }}
            #       docker push ${{ steps.login-ecr.outputs.registry }}/redirect:${{ github.sha }}
            #       docker push ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}

    # cd:
    #     name: Deploy to ECS
    #     runs-on: ubuntu-latest
    #     needs: ci
    #     permissions:
    #         contents: read
    #         id-token: write

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Configure AWS credentials (OIDC)
    #           uses: aws-actions/configure-aws-credentials@v4
    #           with:
    #               role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
    #               aws-region: us-east-1

    #         - name: Deploy ECS services
    #           run: |
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service shortener-service \
    #                 --force-new-deployment
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service redirect-service \
    #                 --force-new-deployment
    #               aws ecs update-service \
    #                 --cluster url-shortener-cluster \
    #                 --service frontend-service \
    #                 --force-new-deployment
